import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Navbar from "./ui/components/Navbar";
import ClickSpark from "./ui/ClickSpark";
import Footer from "./ui/components/Footer";

const interFont = Inter({
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Pitagorici APS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="it"
      className={`${interFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <ClickSpark sparkColor="#ffffff"
        sparkSize={10}
        sparkRadius={15}
        sparkCount={8}
        duration={1000}
        easing="ease-out"
        extraScale={2}>
          <Navbar />
          {children}
          <Footer/>
        </ClickSpark>
      </body>
    </html>
  );
}
